version: '3'
services:
  tickets:
    image: sre/tickets
    tty: true
    stdin_open: true
    entrypoint: /bin/sh -c "npm install && npm run serve"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
