# This is a YAML-formatted file.

replicas: 1

image:
  name: registry.slurm.io/seck8s/provider_backend
  tag: latest
  imagepullpolicy: IfNotPresent

env:
  SERVICE_PORT: 3000
  DB_NAME: provider_prod
  DB_USER: provider_user
  RDB_NAME: provider_prod
  RDB_USER: provider_user
  PROVIDER_SOURCE_HEADER: X-Slurm-Source-Provider
  AUTH_SERVICE_URL: http://authorization-service.main
  PYTHONUNBUFFERED: 1

envSecret: []
  # DB_PASSWORD is mounted from MySQL Bitnami charts secret in separate block in templates/deployment.yaml.
  # Don't add DB_PASSWORD environment variable in envSecret.

service:
  port: 3000
  external_port: 80

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  labels: {}
  host: provider-backend
  domain: edu.slurm.io
  tls: {}
    # secretName: prov-s000-mesh-slurm-io-tls-secret
    # - secretName: tickets-s000-slurm-io-tls-secret
    #   hosts:
    #     - tickets.s000.slurm.io

mysql:
  architecture: standalone
  auth:
    rootPassword: A8kcemcZyk
    database: provider_prod
    username: provider_user
    password: oYcmxsMZw4
    replicationPassword: uBsk9IIa6J
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
  primary:
    persistence:
      enabled: false
      size: 8Gi
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 512Mi
    configuration: |-
      [mysqld]
      max_connections=60
      wait_timeout=180
      interactive_timeout=180
      performance_schema=OFF
      default_authentication_plugin=mysql_native_password
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mysql
      plugin_dir=/opt/bitnami/mysql/plugin
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      datadir=/bitnami/mysql/data
      tmpdir=/opt/bitnami/mysql/tmp
      max_allowed_packet=8M
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
      log-error=/opt/bitnami/mysql/logs/mysqld.log
      character-set-server=UTF8
      collation-server=utf8_general_ci

      gtid_mode = ON
      enforce_gtid_consistency = 1

      [client]
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mysql/plugin

      [manager]
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
  secondary:
    replicaCount: 1
    persistence:
      enabled: false
      size: 8Gi
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 512Mi
    configuration: |-
      [mysqld]
      max_connections=60
      wait_timeout=180
      interactive_timeout=180
      performance_schema=OFF
      default_authentication_plugin=mysql_native_password
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mysql
      plugin_dir=/opt/bitnami/mysql/plugin
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      datadir=/bitnami/mysql/data
      tmpdir=/opt/bitnami/mysql/tmp
      max_allowed_packet=8M
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
      log-error=/opt/bitnami/mysql/logs/mysqld.log
      character-set-server=UTF8
      collation-server=utf8_general_ci

      gtid_mode = ON
      enforce_gtid_consistency = 1

      [client]
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mysql/plugin

      [manager]
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
