version: '2.1'
services:
  controlplane:
    image: ${CI_REGISTRY:-registry.slurm.io}/${CI_PROJECT_NAMESPACE:-sre_main}/${CI_PROJECT_NAME:-controlplane}:${CI_COMMIT_REF_SLUG:-local}.${CI_PIPELINE_ID:-1}
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis:6379

  redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 60
    logging:
      driver: none
