# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import purchase_pb2 as purchase__pb2


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Purchase = channel.unary_unary(
                '/purchase.Greeter/Purchase',
                request_serializer=purchase__pb2.PurchaseRequest.SerializeToString,
                response_deserializer=purchase__pb2.PurchaseReply.FromString,
                )


class GreeterServicer(object):
    """The greeting service definition.
    """

    def Purchase(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Purchase': grpc.unary_unary_rpc_method_handler(
                    servicer.Purchase,
                    request_deserializer=purchase__pb2.PurchaseRequest.FromString,
                    response_serializer=purchase__pb2.PurchaseReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'purchase.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def Purchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/purchase.Greeter/Purchase',
            purchase__pb2.PurchaseRequest.SerializeToString,
            purchase__pb2.PurchaseReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
