# This is a YAML-formatted file.

replicas: 1

image:
  name: registry.slurm.io/mesh_main/authorization_service
  tag: latest
  imagepullpolicy: Always
imagePullSecret: registry-slurm-io

env:
  SERVICE_PORT: 9292
  PROVIDER_AUTH_HEADER: 'X-Slurm-Source-Provider'
  RACK_ENV: production
  JWT_HMAC_SECRET: 'f3116646-e5a9-4418-93e0-8e09a66c5cd6'
  JWT_HMAC_SECRET_EXPIRE: 60
  REDIS_HOST: 'controlplane-redis-master'

#envSecret:
#  REDIS_PASSWORD: controlplane-redis

service:
  port: 9292
  external_port: 80

resources:
#  limits:
#    cpu: 100m
#    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  labels: {}
  host: auth.s000.edu.slurm.io
  tls: []
    # - secretName: tickets-s000-slurm-io-tls-secret
    #   hosts:
    #     - tickets.s000.slurm.io
