# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: purchase.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='purchase.proto',
  package='purchase',
  syntax='proto3',
  serialized_options=b'\n\031io.grpc.examples.purchaseB\rPurchaseProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0epurchase.proto\x12\x08purchase\"\x1f\n\x0fPurchaseRequest\x12\x0c\n\x04\x63\x61rd\x18\x01 \x01(\t\" \n\rPurchaseReply\x12\x0f\n\x07message\x18\x01 \x01(\t2K\n\x07Greeter\x12@\n\x08Purchase\x12\x19.purchase.PurchaseRequest\x1a\x17.purchase.PurchaseReply\"\x00\x42\x32\n\x19io.grpc.examples.purchaseB\rPurchaseProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_PURCHASEREQUEST = _descriptor.Descriptor(
  name='PurchaseRequest',
  full_name='purchase.PurchaseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='card', full_name='purchase.PurchaseRequest.card', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=59,
)


_PURCHASEREPLY = _descriptor.Descriptor(
  name='PurchaseReply',
  full_name='purchase.PurchaseReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='purchase.PurchaseReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['PurchaseRequest'] = _PURCHASEREQUEST
DESCRIPTOR.message_types_by_name['PurchaseReply'] = _PURCHASEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PurchaseRequest = _reflection.GeneratedProtocolMessageType('PurchaseRequest', (_message.Message,), {
  'DESCRIPTOR' : _PURCHASEREQUEST,
  '__module__' : 'purchase_pb2'
  # @@protoc_insertion_point(class_scope:purchase.PurchaseRequest)
  })
_sym_db.RegisterMessage(PurchaseRequest)

PurchaseReply = _reflection.GeneratedProtocolMessageType('PurchaseReply', (_message.Message,), {
  'DESCRIPTOR' : _PURCHASEREPLY,
  '__module__' : 'purchase_pb2'
  # @@protoc_insertion_point(class_scope:purchase.PurchaseReply)
  })
_sym_db.RegisterMessage(PurchaseReply)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='purchase.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=95,
  serialized_end=170,
  methods=[
  _descriptor.MethodDescriptor(
    name='Purchase',
    full_name='purchase.Greeter.Purchase',
    index=0,
    containing_service=None,
    input_type=_PURCHASEREQUEST,
    output_type=_PURCHASEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
