---
version: '2.1'
services:
  provider:
    environment:
      RAILS_ENV: test
    image: sre/provider_backend
    container_name: provider
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid;bundle install && bundle exec rake db:migrate && bundle exec rake db:seed && bundle exec rails s -p 3000 -b 0.0.0.0;"
    volumes:
      - .:/app
    depends_on:
      mysql-primary:
        condition: service_healthy
      mysql-secondary:
        condition: service_healthy
      auth_service:
        condition: service_started
      main_backend:
        condition: service_started
      tickets:
        condition: service_started

  tickets:
    image: sre/tickets
    ports:
      - "8080:8080"
    volumes:
    - ../tickets:/app
    restart: always

  auth_service:
    image: sre/authorization_service
    volumes:
    - ../authorization_service:/app
    ports:
      - "9292:9292"
    environment:
      JWT_HMAC_SECRET: '72884861-ea71-44ab-8f55-b8f2a13f46a8'
      JWT_HMAC_SECRET_EXPIRE: 60
      CONTROL_REDIS: provider_backend_redis_1
      AUTH_AVAILABLE_THREADS_COUNT: 16

  main_backend:
    container_name: main_backend
    tty: true
    stdin_open: true
    image: sre/main_backend
    # volumes:
    #   - ../main_backend:/app
    ports:
      - "80:3000"
    restart: always
    environment:
      JWT_HMAC_SECRET: '72884861-ea71-44ab-8f55-b8f2a13f46a8'
...
