version: '3'
services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  provider:
    image: sre/provider_backend
    tty: true
    stdin_open: true
    command: /bin/bash -c "rm -f /app/tmp/pids/server.pid;bundle install && bundle exec rails s -p 3000 -b 0.0.0.0;"
    environment:
      HOST: test_ticket.io
      REDIS_HOST: redis
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  errbit:
    image: errbit/errbit:latest
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - PORT=4000
      - RACK_ENV=development
      - MONGO_URL=mongodb://mongo:27017/errbit
  mongo:
    image: mongo:4.1
    ports:
      - "27017"

  redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 60
    logging:
      driver: none
